services:
  app:
    image: "gps_listener_image_arm64:latest"
    network_mode: "host"
    volumes:
      - "/opt/payload_credentials:/creds"
    devices:
      - "/dev/ttyUSB2:/dev/leica"
    restart: unless-stopped
    command:
      [
        "--name",
        "Leica GA03",
        "--payload_tform_gps",
        "0",
        "0",
        "0.032",
        "1",
        "0",
        "0",
        "0",
        "--payload-credentials-file",
        "/creds/payload_guid_and_secret",
        "192.168.50.3",
        "--mass",
        ".671",
        "--description",
        "Leica GA03 for GPS integration",
        "--position",
        "-.520",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "--position_of_mass",
        "-.083",
        "0",
        ".02595",
        "--bounding_boxes",
        "-.604",
        "0",
        ".02595",
        "1",
        "0",
        "0",
        "0",
        ".065",
        ".053",
        "0.03844",
        "--gps-credentials-file",
        "leica-gps-payload-credentials.txt",
        "--version",
        "1",
        "0",
        "0",
        "serial",
        "--serial_device",
        "/dev/leica",
      ]
